name: Deploy to Bluehost

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: NODE_ENV=production npm run build

      - name: Verify build output
        run: |
          echo "Checking if out directory exists..."
          ls -la out/
          echo "Checking if index.html exists..."
          ls -la out/index.html
          echo "Checking _next directory..."
          ls -la out/_next/
          echo "Checking images directory..."
          ls -la out/images/
          echo "Checking all files in out directory..."
          find out/ -type f -name "*.html" -o -name "*.js" -o -name "*.css" | head -20
          echo "Build output verification complete!"

      - name: Create .htaccess for Bluehost
        run: |
          echo "Creating .htaccess file for Bluehost..."
          cat > out/.htaccess << 'EOF'
          DirectoryIndex index.html
          RewriteEngine On
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule ^(.*)$ /index.html [QSA,L]
          EOF
          echo ".htaccess file created!"
          echo "Verifying .htaccess file:"
          cat out/.htaccess
          ls -la out/.htaccess

      - name: Copy test file
        run: |
          echo "Copying test deployment file..."
          cp test-deployment.html out/test.html
          echo "Creating simple index backup..."
          cp out/index.html out/index-backup.html
          echo "Test file copied!"

      - name: Set proper permissions
        run: |
          echo "Setting proper file permissions..."
          find out/ -type f -exec chmod 644 {} \;
          find out/ -type d -exec chmod 755 {} \;
          chmod 644 out/index.html
          chmod 644 out/.htaccess
          echo "Permissions set!"

      - name: Final verification before upload
        run: |
          echo "Final verification of files to be uploaded:"
          echo "All files in out directory:"
          find out/ -type f | sort
          echo "Checking .htaccess specifically:"
          ls -la out/.htaccess
          echo "File contents:"
          cat out/.htaccess

      - name: Deploy to Bluehost via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: /public_html/
          log-level: verbose
          dry-run: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.DS_Store
            **/Thumbs.db
